kube-prometheus-stack:
  kubeControllerManager:
    enabled: false
  fullnameOverride: weaveworks-prometheus
  enabled: true
  defaultRules:
    rules:
      kubeApiserverAvailability: false
      kubeApiserverBurnrate: false
      kubeApiserverHistogram: false
      kubeApiserverSlos: false
      kubeControllerManager: false
      kubelet: false
      kubeScheduler: false
      etcd: false
  grafana:
    enabled: false
  prometheus:
    prometheusSpec:
      externalLabels:
        cluster: '${CLUSTER_NAME}'
      replicaExternalLabelName: __replica__
      thanos:
        objectStorageConfig:
          key: objstore.yml
          name: thanos-storage-config
      retention: 2d
      retentionSize: "15GB"
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      # storageSpec:
      #   volumeClaimTemplate:
      #     spec:
      #       storageClassName: gp2
      #       accessModes: ["ReadWriteOnce"]
      #       resources:
      #         requests:
      #           storage: 20Gi
    thanosIngress:
      enabled: false
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
        external-dns.alpha.kubernetes.io/hostname: thanos.${CLUSTER_NAME}.stevefraser.dev
      hosts:
      - 'thanos.${CLUSTER_NAME}.stevefraser.dev'
      paths:
      - /
      pathType: ImplementationSpecific
      tls:
      - secretName: thanos-sidecar-tls
        hosts:
        - 'thanos.${CLUSTER_NAME}.stevefraser.dev'
    thanosServiceExternal:
      enabled: false
      annotations:
        external-dns.alpha.kubernetes.io/hostname: thanos.${CLUSTER_NAME}.stevefraser.dev
prometheus-pushgateway:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: kube-system
thanos:
  enabled: true
  networkPolicy:
    enabled: true
  existingObjstoreSecret: thanos-storage-config
  compactor:
    persistence:
      enabled: false
  #     size: 100Gi
    enabled: true
  #   retentionResolution5m: 90d
  query:
    enabled: true
  queryFrontend:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        external-dns.alpha.kubernetes.io/hostname: thanos.${CLUSTER_NAME}.stevefraser.dev
      hostname: 'thanos.${CLUSTER_NAME}.stevefraser.dev'
      tls: true
  storegateway:
    enabled: false
thanos-bucket-config:
  clusterName: '${CLUSTER_NAME}'
  accessKey: test
  secretKey: test